### ISSUE TITLE
配置文件里的remote与remoteMap有什么关联？

### ISSUE THREAD

**Issue by aa51513** [lidotcircle/portForwarder#1]
二者是否无法同时存在？
我在文档里没有找到更详细的说明

**Comment by lidotcircle** [comment]
remote只可以指定一个目标，就是所有连接都转发到这个地址。
remoteMap可以根据pattern字段来设置哪些连接转发到对应的remote。
两个字段实际上可以共存：

```yaml
remoteMap:
      - pattern: "[ssh]"
        remote: "192.168.44.43:22"
remote: "192.168.44.43:80"
```
这个例子来说，进来的连接会先判断是不是ssh，如果是则转发到192.168.44.43:22，否则就是转发到remote指定的192.168.44.43:80
